AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 8

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

# Layout cops
Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Style cops with commonly changed defaults
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# Lint cops
Lint/AmbiguousBlockAssociation:
  Enabled: true

# Security cops
Security/YAMLLoad:
  Enabled: true
